name: LNbits
summary: Free and Open-Source Lightning Wallet Accounts System with Extensions
description: |
     The WordPress of bitcoin, run for yourself, for others, or as part of a stack.
     LNbits extension framework makes building easy.
version: Leo