name: LNbits CI
on:
  push:
    branches:
      - main
      - dev
  pull_request:


jobs:
  jmeter:
    strategy:
      matrix:
        python-version: ["3.9"]
    uses: ./.github/workflows/jmeter.yml
