name: LNbits CI
on:
  push:
    branches:
      - main
      - dev
  pull_request:


jobs:
  jmeter:
    strategy:
      matrix:
        python-version: ["3.9"]
        poetry-version: ["1.5.1"]
    uses: ./.github/workflows/jmeter.yml
    with:
      python-version: ${{ matrix.python-version }}
      poetry-version: ${{ matrix.poetry-version }}
