name: Test JMeter Action

on:
  workflow_call:

jobs:
  action_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: create reports dir
        run: mkdir reports

      - name: Run JMeter Action on other tests
        uses: rbhadti94/apache-jmeter-action@v0.7.0
        with:
          testFilePath: integration/
          outputReportsFolder: reports/
          args: "--loglevel INFO"

      - name: list reports
        run: |
          ls
          ls reports
          cat jmeter.log
          cat jmeter_log.log
          ls reports
          cat reports/index.html
          cat reports/statistics.json

      - uses: actions/upload-artifact@v1
        with:
          name: jmeter-test-results
          path: reports/
