name: Test2 JMeter Action

on:
  workflow_call:

jobs:
  action_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: create reports dir
        run: mkdir reports

      - name: install jmeter
        run: |
          java -version
          wget https://downloads.apache.org//jmeter/binaries/apache-jmeter-5.5.zip
          unzip apache-jmeter-5.5.zip
          cd apache-jmeter-5.5/bin
          ./jmeter -v
          pwd

      - name: run jmx scripts
        run: |
          for file in $( ls $GITHUB_WORKSPACE/integration/*.jmx); do
            echo "Running test with $file"
            filename=$(basename "$file" ".jmx")
            echo "filename: $file"
            $GITHUB_WORKSPACE/apache-jmeter-5.5/bin/jmeter -n -t $file -l logs/$filename.log -e -o reports-$filename;
            cat logs/$filename.log
            error = $(cat logs/$filename.log | grep "summary =" | awk '{print $15}')
            echo "Test result $error"
          done
